sample="good, monring!"
#capitalize
capitalize_str=sample.capitalize()
print("capitalize():",capitalize_str)
#casefold
casefold_str=sample.casefold()
print("casefold():",casefold_str)
#center
center_str=sample.center(20,'k')
print("center():",center_str)
#count
count_str=sample.count('g')
print("count():",count_str)
#endswith
endswith_str=sample.endswith("!")
print("endswith():",endswith_str)
#encode
encoded_str=sample.encode(encoding="utf-8")
print("encode():",encoded_str)
#expandtabs
tab_expanded="\thello\tworld\t".expandtabs(2)
print("expandtabs():",tab_expanded)
#find()
position=sample.find("ood")
print("find():",position)
#format_map()
school={'name':'kani','age':20}
formated_map="i am {name},and i {age}".format_map(school)
print("format_map():",formated_map)
#index
index_position=sample.index('o')
print("index():",index_position)

sam_str="hello word"
#isalnum()
is_alphanumeric=sam_str.isalnum()
print("isalnum():",is_alphanumeric)
#isalpha
is_alpha=sam_str.isalpha()
print("isalpha():",is_alpha)
#isascii()
is_ascii=sam_str.isascii()
print("isascii():",is_ascii)
#isdecimal
is_decimal=sam_str.isdecimal()
print("isdecimal():",is_decimal)
#isdigit
is_digit=sam_str.isdigit()
print("isdigit():",is_digit)
#isidentifier()
is_identifier=sam_str.isidentifier()
print("isidesntifiers():",is_identifier)
#islower()
is_lower=sam_str.islower()
print("islower():",is_lower)
#isnumeric()
is_numeric=sam_str.isnumeric()
print("isnumeric():",is_numeric)
#isprintable()
is_printable=sam_str.isprintable()
print("isprintable():",is_printable)
#isspace
is_space=sam_str.isspace()
print("isspace():",is_space)
#istitle()
is_title=sam_str.istitle()
print("istitle():",is_title)
#isupper
is_upper=sam_str.isupper()
print("isupper():",is_upper)
#ljust()
left_just=sam_str.ljust(20,'#')
print("ljust():",left_just)
#rjust
right_just=sam_str.rjust(22,'%')
print("rjust():",right_just)
#join
fruits=['apple','orange','mango']
joined_str=",".join(fruits)
print("join():",joined_str)
#splitlines()
multiline_str="hello\ngood morning\n"
print("splitline():",multiline_str)
#partition
partitioned_str=sam_str.partition('.')
print("partition():",partitioned_str)
#lstrip
trimmed_left_str="  hello world".lstrip()
print("lstrip():",trimmed_left_str)
